spring:
  application:
    name: more-mogucnosti-backend

  datasource:
    url: jdbc:mysql://localhost:3306/more_mogucnosti?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    repair: true

server:
  error:
    include-message: always

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace


app:
  jwt:
    secret: ${JWT_SECRET} #tajni kljuc (string) koji se koristi da se potpise i provjeri JWT token
    expiration: 3600000